services:
  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "5001:5001"
    networks:
      - mern-network
    env_file:
      - ./backend/.env 
    restart: always
  

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "5173:5173"
    networks:
      - mern-network
    depends_on:
      - backend
    restart: always

networks:
    mern-network:
      driver: bridge